Introduce ANY_PATTERN_NODE_TYPE and NON_PATTERN_NODE_TYPE
openvinotoolkit/nncf pull request #1010
Opened 2021-11-13 16:12 UTC by kshpv

### Changes

Introduced ANY_PATTERN_NODE_TYPE and NON_PATTERN_NODE_TYPE. ANY_PATTERN_NODE_TYPE  is a node inside the pattern, that matches on any node type, while NON_PATTERN_NODE_TYPE is outside the pattern node. NON_PATTERN_NODE_TYPE is used to reflect some outgoing edges inside the pattern

### Reason for changes

These changes allow adding the L2Norm pattern.

### Related tickets

67283

### Tests

The current tests were updated with new logic.

2021-11-15 10:28 UTC, vshampor requested changes
As discussed, please try the additional isomorphism search step in the instead of maintaining a dict of node keys vs matches.

2021-11-15 11:57 UTC, kshpv commented on nncf/common/graph/patterns.py
> +    ANY_PATTERN_NODE_TYPE = 'ANY_PATTERN_NODE'
I would stay PATTEN word in the name to not confuse users that this node is inside the pattern

2021-11-15 12:33 UTC, vshampor requested changes
Refactor tests to use containers and for-loops and we'll merge this.

2021-11-15 14:43 UTC, vshampor commented
Jenkins please retry a build

2021-11-15 20:10 UTC, kshpv commented
Jenkins please retry a build

2021-11-16 12:24 UTC, vshampor approved these changes

2021-11-16 13:32 UTC, andrey-churkin approved these changes

2021-11-16 13:49 UTC, merged