Added option for --dist-url for parallel execution train tests
openvinotoolkit/nncf pull request #1017
Opened 2021-11-17 17:24 UTC by pfinashx

### Changes

Added option for --dist-url for parallel execution test_train

### Reason for changes

To allow execution train several models simultaneously

### Related tickets

CVS-71283

### Tests

TBD

2021-11-21 17:33 UTC, pfinashx commented
Jenkins please retry a build

2021-11-23 08:40 UTC, vshampor requested changes

2021-11-23 08:40 UTC, vshampor commented on tests/torch/conftest.py
> +        "--cuda-ip", type=str, default=None, help="IP address of distribution URL for train test"
`distribution` -> `distributed mode synchronization`

2021-11-23 08:40 UTC, vshampor commented on tests/torch/test_sota_checkpoints.py
> +            print(f'Setting distribution URL to tcp://127.0.0.1:{cuda_ip}')
Same

2021-11-23 13:06 UTC, vshampor approved these changes

2021-11-23 13:06 UTC, merged