Fix merging quantaizers
openvinotoolkit/nncf pull request #1037
Opened 2021-12-09 07:55 UTC by AlexanderDokuchaev

### Changes

Change merging qunatizers logic for pre_hooks. 

### Reason for changes

```
  File "nncf/common/quantization/quantizer_propagation/solver.py", line 355, in run_on_ip_graph
    quantizer_setup = quant_prop_graph.create_quantizer_setup(self._weight_quantizable_node_names_vs_qconfigs)
  File "nncf/common/quantization/quantizer_propagation/graph.py", line 1115, in create_quantizer_setup
    setup.register_unified_scale_group_with_types([pqid_vs_qpid[pq.id] for pq in pq_set],
  File "nncf/common/quantization/quantizer_propagation/graph.py", line 1115, in <listcomp>
    setup.register_unified_scale_group_with_types([pqid_vs_qpid[pq.id] for pq in pq_set],
KeyError: 1193
```

For submodel  (error on relu node):  
```
            (add)
       /      |        \  
   !(relu)   (conv)   (conv)
     |        |         |
(chunk)      (bn)      (bn)
```

### Related tickets

72029

### Tests

WIP

2021-12-10 08:25 UTC, AlexanderDokuchaev commented
Jenkins please retry a build

2021-12-10 08:44 UTC, vshampor requested changes

2021-12-10 08:44 UTC, vshampor commented on tests/torch/test_nncf_network.py
> +        if node.node_type != 'split':
Better to handle this consistently with the regular NNCFNetwork (nncf/torch/nncf_network.py:551, `get_insertion_point_graph` function)

2021-12-10 08:44 UTC, vshampor commented on tests/torch/quantization/test_quantizer_propagation_graph.py
> +    def test_unifined_scale_type_for_split_node(self):
Typo

2021-12-10 08:44 UTC, vshampor commented on tests/torch/quantization/test_quantizer_propagation_graph.py
> +        assert merged_pq.unified_scale_type == UnifiedScaleType.UNIFY_ALWAYS
You should also check that the resulting unified scale _group_ is correct - i.e. that there is only one group with a required number of PQs, or that there are no groups.

2021-12-10 08:44 UTC, vshampor commented on tests/torch/quantization/test_quantizer_propagation_graph.py
> +    def get_merged_pq(qpsg: QPSG) -> PropagatingQuantizer:
Better to return the QPSG instead of a single quantizer. You can get PQs from a QPSG by calling `collect_all_propagating_quantizers`, for instance.

2021-12-10 09:00 UTC, MaximProshin commented
make sure it covers TF too

2021-12-13 13:37 UTC, vshampor approved these changes

2021-12-13 13:38 UTC, merged