Add ReLU6-based HSwish to fused patterns
openvinotoolkit/nncf pull request #1041
Opened 2021-12-16 14:55 UTC by vshampor

### Changes

As stated in the title.

### Reason for changes

Certain MobileNetV3 variations in PyTorch use an explicit custom HSwish module instead of the `hardswish` function from torch.nn.functional, and this custom module uses ReLU6 internally.

### Related tickets

74044

### Tests

Extended tests.torch.test_compressed_graph.test_synthetic_model_quantization, created ticket 74092 for the TF implementation of synthetic tests in bulk.

2021-12-16 14:59 UTC, alexsu52 approved these changes

2021-12-17 08:06 UTC, kshpv approved these changes

2021-12-17 11:19 UTC, negvet requested changes
The updated TensorFlow pattern is applied in the wrong way, please refer to the figure below.
Develop is on the left (h5 models are attached below):

![image](https://user-images.githubusercontent.com/17028475/146536821-c205c4dd-bb46-4d7a-8956-15b937059e77.png)

[mnet3_int8.zip](https://github.com/openvinotoolkit/nncf/files/7734672/mnet3_int8.zip)

2021-12-17 17:46 UTC, negvet approved these changes

2021-12-17 19:44 UTC, alexsu52 approved these changes

2021-12-20 08:13 UTC, merged