Make dev versions conform to PEP 440
openvinotoolkit/nncf pull request #1050
Opened 2021-12-21 10:26 UTC by vshampor

### Changes

The '-' in dev versions containing commit hash was changed to '+'.

### Reason for changes

Previous version format was not conforming to PEP 440, and the `pip install git+` path of installation failed to install from a wheel. This was not fatal, but a nasty warning was being spawned and a deprecated installation path had to be involved.

### Related tickets

N/A

### Tests

Extended test_install with the `pip install git+` scenarios.

2021-12-21 10:47 UTC, vshampor commented
GPU installation job 226 started.

2021-12-21 11:14 UTC, alexsu52 approved these changes

2021-12-21 11:19 UTC, alexsu52 requested changes
Please provide green install_tf build

2021-12-21 14:01 UTC, vshampor commented
TF install job 188 started.

2021-12-22 08:17 UTC, vshampor commented
Jenkins please retry a build

2021-12-22 08:24 UTC, vshampor commented
Both install builds are green.

2021-12-22 08:24 UTC, vshampor commented
Jenkins please retry a build

2021-12-22 08:33 UTC, vshampor commented
Jenkins please retry a build

2021-12-22 09:01 UTC, alexsu52 approved these changes

2021-12-22 10:24 UTC, merged