Add IR name for GELU.
openvinotoolkit/nncf pull request #1107
Opened 2022-02-10 22:33 UTC by asenina

### Changes

### Reason for changes

### Related tickets

### Tests

2022-02-14 13:27 UTC, vshampor requested changes

2022-02-14 13:27 UTC, vshampor commented on nncf/common/hardware/opset.py
> +    GELU = "Gelu"
Use single quotes.

2022-02-25 11:12 UTC, asenina commented
Jenkins please retry a build

2022-02-25 11:12 UTC, asenina commented on nncf/common/hardware/opset.py
> +    GELU = "Gelu"
Done.

2022-02-27 19:48 UTC, asenina commented
Please take a look  @alexsu52 @vshampor

2022-03-01 15:56 UTC, vshampor approved these changes

2022-03-02 07:49 UTC, merged