FQ with multiple inbound nodes initialization fix
openvinotoolkit/nncf pull request #1119
Opened 2022-02-24 11:06 UTC by negvet

### Changes

FQ with multiple inbound nodes initialization fix

### Reason for changes

Not able to register FQ layer stats

### Related tickets

75958

2022-02-24 11:31 UTC, negvet commented
Jenkins please retry a build

2022-02-25 08:24 UTC, alexsu52 requested changes
Please add tests (ref 58869)

2022-03-04 11:49 UTC, negvet commented
TODO:
- [ ] remove commented code (required for local run)

2022-03-05 07:30 UTC, alexsu52 approved these changes
LGTM

2022-03-05 14:20 UTC, pfinashx approved these changes

2022-03-06 09:56 UTC, negvet commented on tests/tensorflow/sota_checkpoints_eval.json
> +                    "target_init": 0.1,
Thanks for the notice. Indeed it is very low. We have a separate ticket for this issue. I propose to run these tests anyway just for sanity perposes.

2022-03-06 09:56 UTC, negvet commented on tests/tensorflow/test_init.py
> +            with tag('span', style='Background-color: #{}'.format(BG_COLOR_GREEN_HEX)):
Thanks for the comment. Updated!

2022-03-09 09:13 UTC, merged