Add option to set onnx opeset version
openvinotoolkit/nncf pull request #1131
Opened 2022-03-10 15:56 UTC by AlexanderDokuchaev

Add option to change onnx opset version by `save_format` argument.

Example: 
- `onnx_11` to export with opset 11
- `onnx` to export with default opset version (10)

2022-03-11 13:21 UTC, vshampor requested changes

2022-03-11 13:21 UTC, vshampor commented on tests/torch/test_onnx_export.py
> +def test_exporter_parser_format(save_format: str, refs: Any):
Might want to add another test, or a stage of the test - wherein a basic, mock model is being exported using the PTExporter and the resulting ONNX has the desired opset.

2022-03-11 13:21 UTC, vshampor commented on nncf/torch/exporter.py
> +            elif len(splited_format) == 2:
`splited` -> `split`, the 3rd form for the "split" is the same as the 1st.

2022-03-13 21:07 UTC, closed without merging

2022-03-13 21:08 UTC, AlexanderDokuchaev commented
Reopened https://github.com/openvinotoolkit/nncf/pull/1133