[TF] Fix MaskRCNN QAT
openvinotoolkit/nncf pull request #1723
Opened 2023-04-21 13:46 UTC by nikita-savelyevv

### Changes

Fixed MaskRCNN QAT failing on Tensorflow. This was a regression after #1048.

### Related tickets

108752

### Tests

Changed MaskRCNN TF graph tests to operate on the model in training mode. This way we will catch bugs in QAT. Inference bugs should also be caught, but otherwise weekly will fail nevertheless. This leads to a slight improvement of TF precommit runtime: 54min. -> 57min.

2023-04-24 12:19 UTC, nikita-savelyevv commented on nncf/tensorflow/graph/converter.py
> +    bias = False if layer_metatype == op_metatypes.TFMatMulOpMetatype else layer.use_bias
For TFOpLambda layer, there's no `use_bias` property. Added a workaround. This is a regression after #1319.

2023-04-25 13:11 UTC, vshampor requested changes

2023-04-25 13:11 UTC, vshampor commented on nncf/tensorflow/graph/converter.py
> +def _get_linear_layer_attributes(layer: tf.keras.layers.Layer, layer_metatype) -> LinearLayerAttributes:
Type hint missing

2023-04-25 13:40 UTC, nikita-savelyevv commented on nncf/tensorflow/graph/converter.py
> +def _get_linear_layer_attributes(layer: tf.keras.layers.Layer, layer_metatype) -> LinearLayerAttributes:
Done

2023-04-26 10:51 UTC, vshampor approved these changes

2023-04-27 04:12 UTC, alexsu52 requested changes
Let's discuss offline this PR.

2023-04-27 04:12 UTC, alexsu52 commented on nncf/tensorflow/graph/metatypes/common.py
> +    layer_metatypes.TFDenseLayerMetatype
Could you clarify if op_metatypes.TFMatMulOpMetatype operations will be quantized?

2023-04-27 07:09 UTC, nikita-savelyevv commented on nncf/tensorflow/graph/converter.py
> +    bias = False if layer_metatype is op_metatypes.TFMatMulOpMetatype else layer.use_bias
Done

2023-12-18 13:08 UTC, closed without merging