[TF] Increased thresholds for mobilenet_v3
openvinotoolkit/nncf pull request #1727
Opened 2023-04-24 11:48 UTC by nikita-savelyevv

### Changes

As in the title
Additionally made changes to CI-Pipeline repo (MR 356) fixing some issues with thresholds.

### Reason for changes

Accuracy drop is sometimes slightly above the 1% threshold. Increased.

2023-04-24 13:52 UTC, alexsu52 approved these changes

2023-04-24 18:43 UTC, alexsu52 requested changes
Please provide sota_eval and e2e builds for 2.7, 2.8, 2.9, 2.10, 2.11 TF versions.

2023-04-28 07:54 UTC, nikita-savelyevv commented
Obtained green e2e builds for TF 2.7 (id 36), 2.8 (id 5), 2.9 (id 2), 2.10 (id 2)

2023-04-29 09:17 UTC, nikita-savelyevv commented
Green nightly TF 2.11 e2e build 306

2023-05-02 07:06 UTC, alexsu52 approved these changes

2023-05-02 07:07 UTC, merged