[PTQ] Update scales unification rules based on types
openvinotoolkit/nncf pull request #1778
Opened 2023-05-05 17:06 UTC by KodiaqQ

### Changes

- Updated logic for scales unification based on the types

### Reason for changes

- Correctness of the unification functionality

### Related tickets

108258

### Tests

2023-05-16 10:43 UTC, kshpv commented
Could you briefly explain why the previous approach was incorrect?

2023-05-16 10:47 UTC, KodiaqQ commented
> Could you briefly explain why the previous approach was incorrect?

Unification should only take place for those quantizers that are `Concat` inputs but were generated by `Convolution` or `MatMul` layers with a per-tensor quantization scheme for activation.

2023-05-16 11:08 UTC, kshpv approved these changes

2023-05-16 11:08 UTC, kshpv commented on nncf/common/quantization/quantizer_propagation/graph.py
> +        def followed_by_weighted_types(curr_node_key) -> bool:
The name confuses as there are no weighted types used.

2023-05-17 07:41 UTC, alexsu52 requested changes
This PR required deep validation because FQs placment will be chaneged:
- e2e for all backends
- conformance test

2023-06-06 10:19 UTC, alexsu52 commented
> > This PR required deep validation because FQs placment will be chaneged:
> > 
> > * e2e for all backends
> > * conformance test
> 
> e2e pytorch job - No. 328 e2e tf job - No. 337 conformance job - No. 41

Could you provide a summary?

2023-06-09 07:16 UTC, KodiaqQ commented
run pytorch pre-commit tests

2023-06-13 13:53 UTC, alexsu52 approved these changes
LGTM

2023-06-13 13:53 UTC, merged