Enable SQ & update conformance
openvinotoolkit/nncf pull request #1965
Opened 2023-07-11 12:44 UTC by KodiaqQ

### Changes

- Rollback #1945 
- Update conformance test parameters & golds

### Reason for changes

- Need to have enabled SQ

2023-07-11 13:55 UTC, KodiaqQ commented
run pylint pre-commit tests
run pytorch pre-commit tests
run tensorflow pre-commit tests
run openvino pre-commit tests
run onnx pre-commit tests

2023-07-12 09:36 UTC, alexsu52 approved these changes
LGTM

2023-07-12 09:39 UTC, alexsu52 requested changes

2023-07-12 10:01 UTC, KodiaqQ commented on tests/post_training/reference_data.yaml
> +    metric_value: 0.76582
Done

2023-07-12 10:01 UTC, KodiaqQ commented
Conformance re-run - 114

2023-07-12 12:54 UTC, l-bat commented
It would be great to add progress bar for SQ algorithm, as it is done for BC/FBC.
I have confusing log during model quantization:
```python
Statistics collection: 100%|██████████| 300/300 [05:13<00:00,  1.05s/it]
Statistics collection: 100%|██████████| 300/300 [06:36<00:00,  1.32s/it]
Applying Fast Bias correction: 100%|██████████| 144/144 [01:52<00:00,  1.28it/s]
````
I see two consecutive statistics collection. 
I suggest adding a progress bar for the first stage algorithms to avoid confusion.

2023-07-12 13:40 UTC, AlexanderDokuchaev approved these changes

2023-07-13 07:18 UTC, l-bat approved these changes

2023-07-13 07:47 UTC, alexsu52 approved these changes

2023-07-13 07:48 UTC, alexsu52 commented
> It would be great to add progress bar for SQ algorithm, as it is done for BC/FBC. I have confusing log during model quantization:
> 
> ```python
> Statistics collection: 100%|██████████| 300/300 [05:13<00:00,  1.05s/it]
> Statistics collection: 100%|██████████| 300/300 [06:36<00:00,  1.32s/it]
> Applying Fast Bias correction: 100%|██████████| 144/144 [01:52<00:00,  1.28it/s]
> ```
> 
> I see two consecutive statistics collection. I suggest adding a progress bar for the first stage algorithms to avoid confusion.

I think it's better to do it in a separate PR.

2023-07-13 07:49 UTC, merged