Move model type processing to Solver
openvinotoolkit/nncf pull request #1975
Opened 2023-07-14 07:51 UTC by l-bat

### Changes

Mark nodes as ignored in Solver to reduce the log for the automatically generated ignored scope.

### Reason for changes

To improve user experience 

### Tests

conformance current log: 114
conformance with PR changes:

2023-07-17 11:46 UTC, alexsu52 approved these changes
LGTM

2023-07-17 11:46 UTC, kshpv requested changes

2023-07-17 11:46 UTC, kshpv commented on nncf/common/quantization/quantizer_propagation/solver.py
> +        model_type_marker_metatypes: List[OperatorMetatype] = None,
Can we use more generic name that is not depending only on ModelType?
Maybe `metatypes_to_ignore`?

2023-07-17 11:46 UTC, kshpv commented on nncf/quantization/algorithms/min_max/backend.py
> +    def get_ignored_scope(model_type: ModelType, device: TargetDevice) -> List[OperatorMetatype]:
I would update a name to something like `get_ignored_metatypes`

2023-07-17 19:13 UTC, l-bat commented
run pytorch pre-commit tests

2023-07-18 07:49 UTC, kshpv approved these changes

2023-08-03 10:06 UTC, vshampor approved these changes

2023-08-03 10:06 UTC, merged