Shift+Scale and Input+Shift+Scale pattern for PT
openvinotoolkit/nncf pull request #1989
Opened 2023-07-19 14:54 UTC by ljaljushkin

### Changes

Introduced Shift + Scale fused pattern and Input+Shift+Scale pattern to insert Fake Quantize operations optimally for CPU.

### Reason for changes

Customer has a model that is quantized not optimally:
![image](https://github.com/openvinotoolkit/nncf/assets/4014476/59a228fd-1336-4e91-80c4-b67f76febcb8)

FakeQuantize between subtraction and division is redundant and introduces additional cost in runtime.
FakeQuantize between input and pre-processing is not needed in case of single edge from input, because pre-processing can be fused to the FQ after pre-processing.
![image](https://github.com/openvinotoolkit/nncf/assets/4014476/2037597e-cf0d-45f3-b36b-83c1fa7f0de2)
When there are multiple edges from input and one edge is going to pre-processing, it's optimal to have a common fake quantize for all edges. 
![image](https://github.com/openvinotoolkit/nncf/assets/4014476/a150a4b2-1e34-461a-9683-46955abb6ffc)

If pre-processing represented via normalize op from torchvision (e.g. like here https://github.com/PeterL1n/RobustVideoMatting/blob/master/model/mobilenetv3.py#L37), NNCF doesn't insert FQ between subtraction and division and between input and pre-processing.
It happens because pre-processing is implemented via in-place operations, and since FQ is not in-place it can't be applied (see more details here: https://github.com/openvinotoolkit/nncf/pull/1565)
![image](https://github.com/openvinotoolkit/nncf/assets/4014476/17ecd154-a7d8-468c-95d0-31d99ca3185f)

### Related tickets

112934

### Tests

synthetic tests for pre-processing

2023-07-19 16:50 UTC, ljaljushkin commented on nncf/openvino/hardware/fused_patterns.py
> +@OPENVINO_HW_FUSED_PATTERNS.register(HWFusedPatternNames.SHIFT_SCALE)
@KodiaqQ please review OV part

2023-07-19 16:50 UTC, ljaljushkin commented on nncf/onnx/hardware/fused_patterns.py
> +@ONNX_HW_FUSED_PATTERNS.register(HWFusedPatternNames.SHIFT_SCALE)
@kshpv please review ONNX part

2023-07-20 08:58 UTC, kshpv requested changes

2023-07-20 08:58 UTC, kshpv commented on nncf/onnx/hardware/fused_patterns.py
> +    pattern_input_node = pattern.add_node(
you don't need this node here

2023-07-24 08:48 UTC, ljaljushkin commented on nncf/onnx/hardware/fused_patterns.py
> +    pattern_input_node = pattern.add_node(
removed, thanks

2023-07-24 13:30 UTC, kshpv requested changes

2023-07-24 13:30 UTC, kshpv commented on nncf/onnx/hardware/fused_patterns.py
> +        **{GraphPattern.LABEL_ATTR: "MULTIPLY", GraphPattern.METATYPE_ATTR: om.ONNXMulLayerMetatype}
Could be here also `Div` layer?

2023-07-24 13:37 UTC, KodiaqQ approved these changes

2023-07-24 14:17 UTC, ljaljushkin commented on nncf/onnx/hardware/fused_patterns.py
> +        **{GraphPattern.LABEL_ATTR: "MULTIPLY", GraphPattern.METATYPE_ATTR: om.ONNXMulLayerMetatype}
Extended list of types for the pattern

2023-07-24 14:19 UTC, kshpv commented
Thanks!

2023-07-24 14:19 UTC, kshpv approved these changes

2023-07-25 10:38 UTC, alexsu52 approved these changes
LGTM

2023-07-25 10:39 UTC, merged