[PTQ] Enable BC test for ONNX
openvinotoolkit/nncf pull request #2019
Opened 2023-08-01 15:55 UTC by KodiaqQ

### Changes

- Enable BC test for ONNX backend

### Reason for changes

- ONNX backend was updated

### Tests

- tests/onnx/quantization/test_bias_correction.py

2023-08-01 16:50 UTC, kshpv requested changes

2023-08-01 16:50 UTC, kshpv commented on tests/onnx/quantization/test_bias_correction.py
> +            # Disabled, because ONNX backend doesn't support bias correction for MatMul
Please attach a ticket number 116026

2023-08-01 18:08 UTC, kshpv approved these changes

2023-08-02 04:37 UTC, KodiaqQ commented
run pytorch pre-commit tests

2023-08-02 05:51 UTC, merged