Add marks nightly and weakly for torch tests
openvinotoolkit/nncf pull request #2092
Opened 2023-08-30 14:03 UTC by AlexanderDokuchaev

### Changes

- Add marks `nightly` and `weakly` for tests.
- Mark sanity tests as `nightly`
- Split `test_functions.TestParametrized` to fast for precommit and long for nightly
- Time of torch precommit reduced from 60 to 40 mins
- Set `xfail` for sanity tests with `--mode train` in case of segment fault.
  Sporadic segment fault reproduced on torch>=2.0.0 on call `backward` function.

### Related tickets

119128

2023-08-30 14:13 UTC, alexsu52 requested changes
Could you think about move these tests from pre-commit scope to the nightly scope?

2023-08-30 14:44 UTC, vshampor requested changes

2023-08-30 14:44 UTC, vshampor commented on tests/torch/test_sanity_sample.py
> +    runner.retries_run()  # WA for 119128
This will make any kind of failure trigger a retry. Redesign to retry on segmentation faults specifically.

2023-09-01 07:35 UTC, alexsu52 reviewed
Cool staff! Could you provide CI build for nightly precommit tests?

2023-09-01 14:40 UTC, alexsu52 approved these changes
Thanks for the contribution!

2023-09-03 18:26 UTC, vshampor requested changes
So where's the retry functionality in case of a segfault now? Otherwise we are getting a nightly build which will be often red due to a known issue and no one will bother to make it green, leading to overlooked bugs in the backend-nightly scope.

2023-09-04 13:41 UTC, AlexanderDokuchaev commented
> So where's the retry functionality in case of a segfault now? Otherwise we are getting a nightly build which will be often red due to a known issue and no one will bother to make it green, leading to overlooked bugs in the backend-nightly scope.

All changes exist in descript of PR. Yes, seg fault from original ticket will be moved to nightly job.

2023-09-04 13:48 UTC, daniil-lyakhov approved these changes

2023-09-07 08:54 UTC, vshampor commented
Should be merged after #2112

2023-09-07 11:20 UTC, AlexanderDokuchaev commented
> Should be merged after https://github.com/openvinotoolkit/nncf/pull/2112

why?

2023-09-07 14:25 UTC, vshampor commented
@AlexanderDokuchaev see my [comment](https://github.com/openvinotoolkit/nncf/pull/2092#pullrequestreview-1608562245) above

2023-09-07 15:27 UTC, AlexanderDokuchaev commented
> @AlexanderDokuchaev see my https://github.com/openvinotoolkit/nncf/pull/2092#pullrequestreview-1608562245 above

Your comment it's not the reason to block this PR.

2023-09-11 07:14 UTC, alexsu52 commented
@vshampor, let's merge it.

2023-09-11 07:14 UTC, alexsu52 approved these changes

2023-09-11 09:00 UTC, AlexanderDokuchaev commented
run pylint pre-commit tests
run pytorch pre-commit tests
run openvino pre-commit tests
run onnx pre-commit tests

2023-09-11 09:51 UTC, merged