Update OpenVINO version
openvinotoolkit/nncf pull request #2147
Opened 2023-09-19 15:01 UTC by KodiaqQ

### Changes

- Updated OpenVINO version to 23.1

2023-09-19 15:57 UTC, alexsu52 requested changes
Please update openvino and openvino-dev version in all NNCF.

2023-09-20 08:37 UTC, alexsu52 commented
run: test_examples/92/

2023-09-20 09:55 UTC, alexsu52 requested changes

2023-09-20 09:55 UTC, alexsu52 commented on examples/post_training_quantization/tensorflow/mobilenet_v2/requirements.txt
> +openvino-dev==2023.1
```suggestion
openvino-dev==2023.0.2
```
take into account test_examples/92/ results

2023-09-20 10:50 UTC, KodiaqQ commented on examples/post_training_quantization/tensorflow/mobilenet_v2/requirements.txt
> +openvino-dev==2023.1
Build - 93

2023-09-21 07:28 UTC, alexsu52 approved these changes

2023-09-21 07:28 UTC, merged