Added ov_version parameter to the env tests
openvinotoolkit/nncf pull request #2209
Opened 2023-10-18 15:52 UTC by KodiaqQ

### Changes

- Added `ov_version` variable for the pytest in `test_examples`;
- Added `ov_version` variable for the pytest in the `test_install_*`;

### Reason for changes

- More flexible tests

### Related tickets

- 122860

### Tests

- Updated

2023-10-19 09:22 UTC, vshampor requested changes

2023-10-19 09:22 UTC, vshampor commented on tests/cross_fw/examples/conftest.py
> +def ov_module(request):
`ov_version_override`

2023-10-19 09:22 UTC, vshampor commented on tests/cross_fw/examples/test_examples.py
> +def test_examples(tmp_path, example_name, example_params, backends_list, is_check_performance, ov_module):
A good opportunity to set up type hints

2023-10-19 13:28 UTC, alexsu52 approved these changes
LGTM

2023-10-23 09:23 UTC, KodiaqQ commented
run pylint pre-commit tests
run pytorch pre-commit tests
run tensorflow pre-commit tests
run openvino pre-commit tests
run onnx pre-commit tests

2023-10-23 12:52 UTC, vshampor approved these changes

2023-10-24 09:09 UTC, merged