Add model-hub tests to check wrap_model
openvinotoolkit/nncf pull request #2275
Opened 2023-11-16 14:29 UTC by AlexanderDokuchaev

### Changes

- Add models_hub_tests to check `wrap_model`,  like https://github.com/openvinotoolkit/openvino/tree/master/tests/model_hub_tests/torch_tests
- Add `Model Hub` github action to manual run 

### Related tickets

124852

### Tests

tests/torch/models_hub_test

2023-11-16 14:32 UTC, AlexanderDokuchaev commented
Github action can be run before merge to develop. 
Checked on default host (with low limit of RAM), test runs but killed by OOM.

2023-11-17 13:01 UTC, vshampor requested changes

2023-11-20 13:23 UTC, AlexanderDokuchaev commented
https://github.com/openvinotoolkit/nncf/actions/runs/6930010257/job/18848850899?pr=2275

2023-11-28 12:50 UTC, AlexanderDokuchaev commented on tests/torch/models_hub_test/common.py
> +            models.append(ModelInfo(model_name, model_link, mark, reason))
The comment has been reviewed and no further action will be taken. 
@MaximProshin

2023-11-28 12:50 UTC, AlexanderDokuchaev commented on tests/torch/models_hub_test/test_hf_transformers.py
> +        if "clip_vision_model" in mi.tags:
The comment has been reviewed and no further action will be taken. 
@MaximProshin

2023-11-28 12:50 UTC, AlexanderDokuchaev commented on tests/torch/models_hub_test/test_torchvision_models.py
> +    video_url = "https://download.pytorch.org/tutorial/pexelscom_pavel_danilyuk_basketball_hd.mp4"
The comment has been reviewed and no further action will be taken. 
@MaximProshin

2023-11-28 12:51 UTC, AlexanderDokuchaev commented on tests/torch/models_hub_test/__init__.py
> +# Copyright (c) 2023 Intel Corporation
The comment has been reviewed and no further action will be taken. 
@MaximProshin

2023-11-28 12:51 UTC, AlexanderDokuchaev commented on tests/torch/models_hub_test/common.py
> +            params.append(mi)
The comment has been reviewed and no further action will be taken. 
@MaximProshin

2023-11-28 12:51 UTC, AlexanderDokuchaev commented on tests/torch/models_hub_test/common.py
> +class BaseTestModel(ABC):
The comment has been reviewed and no further action will be taken. 
@MaximProshin

2023-11-28 12:51 UTC, AlexanderDokuchaev commented on tests/torch/models_hub_test/test_hf_transformers.py
> +class TestTransformersModel(BaseTestModel):
The comment has been reviewed and no further action will be taken. 
@MaximProshin

2023-11-28 12:51 UTC, AlexanderDokuchaev commented on tests/torch/models_hub_test/test_hf_transformers.py
> +def fixture_image(request):
The comment has been reviewed and no further action will be taken. 
@MaximProshin

2023-11-28 12:51 UTC, AlexanderDokuchaev commented on tests/torch/models_hub_test/common.py
> +        self.check_graph(nncf_model.nncf.get_original_graph())
The comment has been reviewed and no further action will be taken. 
@MaximProshin

2023-11-28 12:52 UTC, AlexanderDokuchaev commented on tests/torch/models_hub_test/test_speech_transformer.py
> +        os.system(f"git clone https://github.com/mvafin/Speech-Transformer.git {self.repo_dir.name}")
The comment has been reviewed and no further action will be taken. 
@MaximProshin

2023-11-28 12:52 UTC, AlexanderDokuchaev commented on tests/torch/models_hub_test/test_speech_transformer.py
> +        sys.path.append(self.repo_dir.name)
The comment has been reviewed and no further action will be taken. 
@MaximProshin

2023-11-28 12:52 UTC, AlexanderDokuchaev commented on tests/torch/models_hub_test/test_timm.py
> +        name_join = "_".join(name_set)
The comment has been reviewed and no further action will be taken. 
@MaximProshin

2023-11-28 12:52 UTC, AlexanderDokuchaev commented on tests/torch/models_hub_test/test_timm.py
> +    def load_model(self, model_name: str):
The comment has been reviewed and no further action will be taken. 
@MaximProshin

2023-11-28 12:52 UTC, AlexanderDokuchaev commented on tests/torch/models_hub_test/test_speech_transformer.py
> +    def load_model(self, model_name: str):
The comment has been reviewed and no further action will be taken. 
@MaximProshin

2023-11-28 12:52 UTC, AlexanderDokuchaev commented on tests/torch/models_hub_test/test_hf_transformers.py
> +        torch.manual_seed(0)
The comment has been reviewed and no further action will be taken. 
@MaximProshin

2023-11-28 12:52 UTC, AlexanderDokuchaev commented on tests/torch/models_hub_test/test_hf_transformers.py
> +    request.cls.image = Image.open(requests.get(url, stream=True).raw)
The comment has been reviewed and no further action will be taken. 
@MaximProshin

2023-11-28 12:53 UTC, AlexanderDokuchaev commented on tests/torch/models_hub_test/test_speech_transformer.py
> +        subprocess.check_call(["git", "checkout", "071eebb7549b66bae2cb93e3391fe99749389456"], cwd=self.repo_dir.name)
The comment has been reviewed and no further action will be taken. 
@MaximProshin

2023-11-28 12:53 UTC, AlexanderDokuchaev commented on tests/torch/models_hub_test/test_timm.py
> +def get_all_models() -> list:
The comment has been reviewed and no further action will be taken. 
@MaximProshin

2023-11-28 12:53 UTC, AlexanderDokuchaev commented on tests/torch/models_hub_test/test_torchvision_models.py
> +# Copyright (c) 2023 Intel Corporation
The comment has been reviewed and no further action will be taken. 
@MaximProshin

2023-11-28 12:53 UTC, AlexanderDokuchaev commented on tests/torch/models_hub_test/test_speech_transformer.py
> +class TestSpeechTransformerModel(BaseTestModel):
The comment has been reviewed and no further action will be taken. 
@MaximProshin

2023-11-28 12:53 UTC, AlexanderDokuchaev commented on tests/torch/models_hub_test/test_timm.py
> +    def test_nncf_wrap(self, name):
The comment has been reviewed and no further action will be taken. 
@MaximProshin

2023-11-28 12:54 UTC, AlexanderDokuchaev commented on tests/torch/models_hub_test/test_timm.py
> +def filter_timm(timm_list: list) -> list:
The comment has been reviewed and no further action will be taken. 
@MaximProshin

2023-11-29 05:27 UTC, merged