as/do_not_wrap_example_input
openvinotoolkit/nncf pull request #2278
Opened 2023-11-17 17:04 UTC by alexsu52

### Changes
Create new instance `torch.Tensor` in `nncf_model_input`

### Reason for changes

`nncf_model_input` patched `torch.Tensor` with `TracedTensor` which does not support deepcopy.

### Related tickets

125357

### Tests
test_wrap_model_with_example_input

2023-11-17 18:00 UTC, vshampor requested changes
I have proposed one possible solution below, but as I have been writing this, I have thought of another one. 

We could try and keep a weakref to `self` in the `TracedTensor`, and also preserve weakrefs to input tensors inside the `self.nncf._compressed_context`  somewhere around the `args, kwargs = self.nncf._wrap_inputs_fn(args, kwargs)` line in `NNCFNetwork.forward`. We could then in `nncf.torch.dynamic_graph.context.TracingContext.__exit__` iterate over these "input tensor weakrefs", see if they are still valid (they probably will be valid, but just in case), and if so, replace the `.__class__` attribute on the corresponding tensors back to `torch.Tensor` (or to a previously saved "original class"). 

In this way, upon exiting NNCFNetwork all `TracedTensors` will get automatically turned back into regular `Tensors`. There may be issues with copyability/shallow copies of the `TracedTensor` while it still has a weakref, though, would have to test for that first.

On the other hand, the complexity of this solution is moderate, and it would indeed be easier just to do the torch.Tensor copy for the time being, and hope that the users will forgive us the extra input tensor copies. If you think that the perf overhead will not be an issue in practice , then I'll approve this if you only address the comment about the test case.

2023-11-24 10:42 UTC, vshampor submitted a review, later dismissed
Great job cleaning out the hidden issues in the context. I see the new test on nested contexts and tensor tracing, but still consider adding the test that would fail with a `__deepcopy__` related error we've been seeing in PTQ tests without the fix, and would *not* fail with the fix, so that we catch this kind of errors early on (e.g. at precommit stage).

2023-11-26 14:31 UTC, alexsu52 commented on nncf/torch/dynamic_graph/context.py
> +        save_context = self._threading.thread_local.save_context.pop(-1)
done

2023-11-26 15:07 UTC, alexsu52 commented on tests/torch/test_tracing_context.py
> +    assert len(ctx._threading.thread_local.traced_tensor_weakrefs) == 0
Thanks for the comment. Done.

2023-11-26 15:10 UTC, alexsu52 commented on nncf/torch/dynamic_graph/trace_tensor.py
> +
Could you provide your opinion about the method signature?

2023-11-26 15:32 UTC, alexsu52 commented
> Great job cleaning out the hidden issues in the context. I see the new test on nested contexts and tensor tracing, but still consider adding the test that would fail with a `__deepcopy__` related error we've been seeing in PTQ tests without the fix, and would _not_ fail with the fix, so that we catch this kind of errors early on (e.g. at precommit stage).

The test has been added.

2023-11-27 22:09 UTC, AlexanderDokuchaev requested changes

2023-11-27 22:09 UTC, AlexanderDokuchaev commented on nncf/torch/dynamic_graph/trace_tensor.py
>          tensor.tensor_meta = tensor_meta
Could you add docstring?

2023-11-28 11:09 UTC, alexsu52 commented on nncf/torch/dynamic_graph/trace_tensor.py
> +    tensor.__class__ = tensor.original_class
done

2023-11-28 11:10 UTC, alexsu52 commented on nncf/torch/dynamic_graph/trace_tensor.py
>          tensor.tensor_meta = tensor_meta
done

2023-11-28 12:19 UTC, AlexanderDokuchaev approved these changes

2023-11-28 12:32 UTC, merged