Extend weight compression with INT8 symmetric scheme
openvinotoolkit/nncf pull request #2288
Opened 2023-11-23 21:20 UTC by l-bat

### Changes

Added `INT8_SYM` compression mode

### Reason for changes

 `INT8_SYM` mode can provide a better performance and required for dynamic quantization

### Related tickets

124823

### Tests

Updated tests/openvino/native/quantization/test_weights_compression.py

2023-11-23 21:24 UTC, l-bat commented on docs/compression_algorithms/CompressWeights.md
> +    <td class="tg-0pky">int8_asym</td>
@AlexKoff88 Should we provide results for `int8_sym` mode on these models?

2023-11-23 21:24 UTC, l-bat commented on nncf/torch/quantization/quantize_model.py
> +    if mode != CompressWeightsMode.INT8_ASYM:
@AlexKoff88 Is it required to add `INT8_SYM` mode for Torch backend?

2023-11-27 08:36 UTC, l-bat commented on docs/compression_algorithms/CompressWeights.md
> +    <td class="tg-0pky">int8_asym</td>
No (discussed offline)

2023-11-27 08:36 UTC, l-bat commented on nncf/torch/quantization/quantize_model.py
> +    if mode != CompressWeightsMode.INT8_ASYM:
No (discussed offline)

2023-11-27 14:40 UTC, ljaljushkin requested changes

2023-11-27 14:40 UTC, ljaljushkin commented on nncf/quantization/algorithms/weight_compression/openvino_backend.py
> +        _assign_mixed_precision(internal_weight_params, ratio, primary_config)
Could please refactor this part to make it more clear?
- `_assign_mixed_precision` is not actually about mixed precision when ratio=1, I'd move outside this logic
- internal weight params and if condition are needed for mixed precision only

BTW, which mode is assigned for embeddings in INT4_ASYM / INT4_SYM? Is it always INT8_ASYM? I'd mention this in docs.

2023-11-29 22:26 UTC, ljaljushkin commented on nncf/quantization/algorithms/weight_compression/openvino_backend.py
> +        INT8_SYM mode refers to unsigned int4 symmetric weight compression with a fixed zero point equals to 128 -
```suggestion
        INT8_SYM mode refers to unsigned int8 symmetric weight compression with a fixed zero point equals to 128 -
```

2023-11-30 15:52 UTC, ljaljushkin approved these changes
Special thanks for refactoring and fixing issue with printing statistics

2023-12-05 07:51 UTC, andreyanufr approved these changes

2023-12-06 05:56 UTC, alexsu52 commented on nncf/parameters.py
> +    INT8 = "int8"  # Deprecated mode
What do you think about leaving INT8 as an alias for INT8_ASYM?

2023-12-07 04:52 UTC, merged