Compress weights of Conv layers to 8 bit
openvinotoolkit/nncf pull request #2416
Opened 2024-01-22 15:02 UTC by l-bat

### Changes

To further reduce the model footprint and handle situations when Linear layers are expressed by Convolution operation, we should add Conv layers to the scope of weight compression.

### Reason for changes

### Related tickets

124822

### Tests

Added tests to tests/openvino/native/quantization/test_weights_compression.py

2024-01-23 16:19 UTC, ljaljushkin commented
Please also update the https://github.com/openvinotoolkit/nncf/blob/develop/docs/compression_algorithms/CompressWeights.md
it does not mention conv layers

2024-01-24 22:02 UTC, AlexanderDokuchaev requested changes

2024-01-31 08:01 UTC, l-bat commented on nncf/quantization/algorithms/weight_compression/weight_lowering.py
> +    :param reduction_axis: Axes, along which to reduce (collect) different statistics (e.g. min, max).
done

2024-01-31 08:01 UTC, l-bat commented on nncf/quantization/algorithms/weight_compression/weight_lowering.py
> +    weight: Tensor, reduction_axis: Union[int, Tuple[int]], config: WeightCompressionConfig
done

2024-02-01 15:08 UTC, AlexanderDokuchaev approved these changes

2024-02-01 15:15 UTC, ljaljushkin approved these changes

2024-02-01 15:18 UTC, merged