[Torch] Subtract eps from quantizer parameters instead of zeroing it
openvinotoolkit/nncf pull request #2479
Opened 2024-02-15 15:52 UTC by daniil-lyakhov

### Changes

Eps is subtracted from quantizer parameters instead of zeroing.

### Reason for changes

To have non zero eps parameters inside quantizer modules. That allows to do the quantization aware training.

### Related tickets

129584

### Tests

TODO: 

- [ ] Test quantize conformance

2024-02-19 10:23 UTC, AlexanderDokuchaev requested changes

2024-02-19 10:23 UTC, AlexanderDokuchaev commented on nncf/quantization/algorithms/min_max/torch_backend.py
> +            quantizer.scale = torch.nn.Parameter(parameters.input_high.data - quantizer.eps)
Could you add unit test to check eps?

2024-02-19 14:34 UTC, AlexanderDokuchaev approved these changes

2024-02-20 03:46 UTC, alexsu52 approved these changes
LGTM

2024-02-20 03:46 UTC, merged