Update documentation for release v1.5.0
openvinotoolkit/nncf pull request #252
Opened 2020-11-05 17:06 UTC by vshampor

2020-11-05 17:07 UTC, vshampor commented
Please add or correct anything I've missed.

2020-11-05 21:10 UTC, ljaljushkin requested changes
please merge my changes https://github.com/vshampor/nncf_pytorch/pull/2

2020-11-06 07:39 UTC, ljaljushkin approved these changes

2020-11-06 09:34 UTC, asenina approved these changes

2020-11-06 11:01 UTC, vshampor commented on nncf/config_schema.py
> +                                                     "values from the set ('CPU', 'GPU', 'VPU', 'ANY', 'NONE'). If you "
Done

2020-11-06 11:01 UTC, vshampor commented on ReleaseNotes.md
> +- Switched to using the propagation-based mode for quantizer setup by default. Compared to the previous default, pattern-based mode, the propagation-based mode better ensures that all the inputs to o
Done

2020-11-06 11:01 UTC, vshampor commented on nncf/config_schema.py
> +                                                     "values from the set ('CPU', 'GPU', 'VPU', 'ANY', 'NONE'). If you "
Done

2020-11-06 12:40 UTC, merged