[NNCF] NNCF common accuracy aware training code pass mypy checks
openvinotoolkit/nncf pull request #2521
Opened 2024-02-26 17:25 UTC by siddhant-0707

### Changes
Added type annotation to files in `nncf/common/accuracy_aware_training`.
Some checks still not passing mainly due to problem with class annotations.

### Related tickets

#2492

### Tests

mypy

2024-02-27 10:04 UTC, vshampor commented
@siddhant-0707 please extend the `.mypy.ini` file in the repo root in this PR to include the code path that you enabled with mypy so that our `mypy` precommit check can confirm that the files you changed indeed pass.

2024-02-29 09:30 UTC, vshampor requested changes

2024-02-29 09:30 UTC, vshampor commented on .mypy.ini
> +files = nncf/common/accuracy_aware_training
You shouldn't replace the path, you should extend it.

2024-02-29 09:30 UTC, vshampor commented on nncf/common/accuracy_aware_training/runner.py
> +        **kwargs: Any,
This type hint is incorrect, review your general Python knowledge as to what type the `**kwargs` parameter is constrained to.

2024-03-19 09:18 UTC, mlukasze commented
hey @siddhant-0707 will you have time to respond for changes request?

2025-02-07 11:07 UTC, AlexanderDokuchaev commented
Was done in https://github.com/openvinotoolkit/nncf/pull/3212

2025-02-07 11:07 UTC, closed without merging