copyright owner
openvinotoolkit/nncf pull request #2586
Opened 2024-03-19 23:08 UTC by AlexanderDokuchaev

2024-03-20 05:59 UTC, MaximProshin requested changes
@AlexanderDokuchaev , why is it needed?

2024-03-22 06:03 UTC, alexsu52 approved these changes

2024-03-28 08:58 UTC, MaximProshin commented
@AlexanderDokuchaev , I think it should be closed. Agree?

2024-03-29 08:13 UTC, MaximProshin approved these changes

2024-04-03 09:42 UTC, merged