Add more hyperparams for EvolutionOptimizer
openvinotoolkit/nncf pull request #2618
Opened 2024-04-06 14:01 UTC by UsingtcNower

### Changes

### Reason for changes

### Related tickets

### Tests

2024-04-15 12:31 UTC, ljaljushkin requested changes
Thanks for the contribution! Please address one comment.

2024-04-16 02:37 UTC, UsingtcNower commented on nncf/config/schemata/defaults.py
> +PRUNING_LEGR_POPULATION_SIZE = 64
Good catch~ And thanks for your review! I've add it.

2024-04-16 02:39 UTC, UsingtcNower commented
> Thanks for the contribution! Please address one comment.

Hi @ljaljushkin ,Thanks for your review! I've addressed the comment, Could you please help to check it?

2024-04-16 07:08 UTC, ljaljushkin commented
@UsingtcNower `pre-commit-linters` job is failing because of some issues with code style.
please fix it: https://github.com/openvinotoolkit/nncf/blob/develop/CONTRIBUTING.md#code-style

2024-04-16 12:14 UTC, UsingtcNower commented
> @UsingtcNower `pre-commit-linters` job is failing because of some issues with code style. please fix it: https://github.com/openvinotoolkit/nncf/blob/develop/CONTRIBUTING.md#code-style

Hi @ljaljushkin Thanks for your review! I've reformat the code, could you please help to check it? BTW, I found the check tool also pointed out a code outside this change, so I'm not sure whether I need submit it or not.

2024-04-16 12:40 UTC, ljaljushkin commented
> > @UsingtcNower `pre-commit-linters` job is failing because of some issues with code style. please fix it: https://github.com/openvinotoolkit/nncf/blob/develop/CONTRIBUTING.md#code-style
> 
> Hi @ljaljushkin Thanks for your review! I've reformat the code, could you please help to check it? BTW, I found the check tool also pointed out a code outside this change, so I'm not sure whether I need submit it or not.

Feel free to submit all diff after `make pre-commit` run. 
on our practice, it affects only modified files.

2024-04-16 15:30 UTC, ljaljushkin approved these changes

2024-04-16 16:23 UTC, merged