Support per-channel mode in AWQ, GPTQ and Scale Estimation algos
openvinotoolkit/nncf pull request #2785
Opened 2024-07-04 09:58 UTC by l-bat

### Changes

* Support `group_size=-1` in AWQ, GPTQ and Scale Estimation algorithms 

### Reason for changes

* To enable more accurate per-channel quantization for devices that do not support group quantization

### Related tickets

* 145725

### Tests

tests/openvino/native/quantization/test_weights_compression.py

2024-07-05 08:44 UTC, alexsu52 reviewed
LGTM, please provide results of post_training_weight_compression for this PR.

2024-07-05 10:29 UTC, andreyanufr approved these changes

2024-07-05 15:01 UTC, l-bat commented
ci build: 92

2024-07-05 16:29 UTC, l-bat commented
ci build: 93

2024-07-12 13:12 UTC, ljaljushkin requested changes
I'd add a conformance tests for per-channel compression, for instance for Scale Estimation algo, if the test similarity is > 50%.

2024-07-12 15:01 UTC, ljaljushkin approved these changes

2024-07-12 15:31 UTC, merged