[PT] bump torch 2.4.0
openvinotoolkit/nncf pull request #2852
Opened 2024-07-29 17:19 UTC by AlexanderDokuchaev

### Changes

### Reason for changes

### Related tickets

### Tests

2024-07-30 17:23 UTC, AlexanderDokuchaev commented
manual/job/post_training_quantization/436/
nightly/job/torch_nightly/296/
nightly/job/TriggerBetta/790/

2024-07-31 12:22 UTC, daniil-lyakhov approved these changes

2024-07-31 14:39 UTC, KodiaqQ requested changes
Please update `README.md`, `Installation.md`, `BKC_TORCH_SPEC` and other places with the new `torch` version.

2024-08-02 08:55 UTC, KodiaqQ approved these changes

2024-08-02 08:56 UTC, KodiaqQ commented
@AlexanderDokuchaev, also after this PR it is required to make changes in our CI as well.

2024-08-02 08:56 UTC, merged