Added BF16 & FP16 models to PTQ tests
openvinotoolkit/nncf pull request #2922
Opened 2024-08-28 12:29 UTC by KodiaqQ

### Changes

- Added BF16/FP16 models to PTQ tests scope.

### Reason for changes

- Extend e2e with different precisions.

### Related tickets

- 147481

### Tests

- TBD

2024-11-27 13:28 UTC, KodiaqQ commented
@openvinotoolkit/nncf-maintainers, can someone review this, please. Thank you.

2024-11-28 14:48 UTC, AlexanderDokuchaev requested changes

2024-11-28 14:48 UTC, AlexanderDokuchaev commented on tests/post_training/pipelines/base.py
> +class PrecisionType(Enum):
Use torch.dtype directly no need to create yet another enum.

2024-11-28 14:48 UTC, AlexanderDokuchaev commented on tests/post_training/test_quantize_conformance.py
> +        base_precision = test_model_param.get("base_precision", PrecisionType.FP32)
use `param` to store `base_precision`. 
Like it done for `is_stateful`

https://github.com/openvinotoolkit/nncf/blob/develop/tests/post_training/model_scope.py#L58
https://github.com/openvinotoolkit/nncf/blob/develop/tests/post_training/pipelines/causal_language_model.py#L27

2024-11-28 18:35 UTC, AlexanderDokuchaev commented
manual/job/post_training_quantization/563/

2024-11-28 18:35 UTC, AlexanderDokuchaev approved these changes

2024-11-28 18:35 UTC, merged