Docs for statistics caching
openvinotoolkit/nncf pull request #3052
Opened 2024-10-31 14:14 UTC by kshpv

### Changes

Add section regarding statistics caching for WeightCompression

2024-10-31 14:46 UTC, kshpv commented on docs/usage/post_training_compression/weights_compression/Usage.md
> +To optimize performance and reuse statistics data across multiple configurations, the `statistics_path` option can be used. This feature allows caching of computed statistics, so they can be loaded f
done

2024-10-31 14:55 UTC, MaximProshin commented on docs/usage/post_training_compression/weights_compression/Usage.md
> +#### Caching Statistics
Do we really need bullets at all?

2024-11-01 06:04 UTC, MaximProshin approved these changes
LGTM

2024-11-07 17:19 UTC, kshpv commented on docs/usage/post_training_compression/weights_compression/Usage.md
>  compressed_model = compress_weights(model, mode=CompressWeightsMode.E2M1, group_size=32, all_layers=True)
I added spoiler for a code example of **Prepare the calibration dataset for data-based algorithms** because it is big

2024-11-07 17:20 UTC, kshpv commented on docs/usage/post_training_compression/weights_compression/Usage.md
> +#### Caching Statistics
I keep this bullet and add extra one - Data-aware methods
For me looks better now

2024-11-07 17:21 UTC, kshpv commented on docs/usage/post_training_compression/weights_compression/Usage.md
> +To optimize performance and reuse statistics data across multiple configurations, the `statistics_path` option can be used. This feature allows caching of computed statistics, so they can be loaded f
Converted `performance` to `compression time`

2024-11-08 06:34 UTC, MaximProshin commented on docs/usage/post_training_compression/weights_compression/Usage.md
> +To optimize performance and reuse statistics data across multiple configurations, the `statistics_path` option can be used. This feature allows caching of computed statistics, so they can be loaded f
I suppose you reverted these changes.

2024-11-08 09:21 UTC, kshpv commented on docs/usage/post_training_compression/weights_compression/Usage.md
> +To optimize performance and reuse statistics data across multiple configurations, the `statistics_path` option can be used. This feature allows caching of computed statistics, so they can be loaded f
Updated the whole statement. Please rereview

2024-11-08 09:24 UTC, MaximProshin approved these changes

2024-11-08 10:01 UTC, ljaljushkin requested changes

2024-11-08 10:01 UTC, ljaljushkin commented on docs/usage/post_training_compression/weights_compression/Usage.md
> +#### Caching Statistics
Please add data-free bullet then

2024-11-08 12:41 UTC, ljaljushkin approved these changes

2024-11-08 13:07 UTC, merged