Suppressed UserWarning: TORCH_CUDA_ARCH_LIST
openvinotoolkit/nncf pull request #3160
Opened 2024-12-17 16:10 UTC by devesh-2002

### Changes

TORCH_CUDA_ARCH_LIST warning is suppressed using `torch.cuda.get_arch_list()`. 

Please let me know, if any changes are required.

### Related tickets

Solves issue #3141

2024-12-23 12:09 UTC, alexsu52 requested changes
Thanks for the contribution! 

I believe that this solution can be extended to all cases of using NNCF, not just for mobilenet_v2 example. I'm sure such PR will be more valuable for NNCF users.

I would suggest the following:
- Move the suppression code in the method which compiles NNCF extension for GPU https://github.com/openvinotoolkit/nncf/blob/909ce0ac03f78b890d9fb774da153aaaf9b59e1a/nncf/torch/extensions/__init__.py#L102
- Rework warning suppression via warning filtering:
```
with warnings.catch_warnings():
    warnings.filterwarnings("ignore", message="TORCH_CUDA_ARCH_LIST is not set")
    pool = ThreadPool(processes=1)
    async_result = pool.apply_async(self._loader.load)
    self._loaded_namespace = async_result.get(timeout=timeout)
```

2024-12-25 11:16 UTC, devesh-2002 commented
I have made the requested changes. Please let me know if any further modifications are needed

2025-01-06 11:54 UTC, alexsu52 commented on nncf/torch/extensions/__init__.py
> +                        self._loaded_namespace = async_result.get(timeout=timeout)
I suggest does not set `TORCH_CUDA_ARCH_LIST` environment variable and just skip the warning.
```suggestion
                    with warnings.catch_warnings():
                        warnings.filterwarnings("ignore", message="TORCH_CUDA_ARCH_LIST is not set")
                        pool = ThreadPool(processes=1)
                        async_result = pool.apply_async(self._loader.load)
                        self._loaded_namespace = async_result.get(timeout=timeout)
```

2025-01-06 11:54 UTC, alexsu52 commented on examples/post_training_quantization/torch/mobilenet_v2/main.py
> -
Please, return this blank line to avoid changing this file.

2025-01-07 07:14 UTC, alexsu52 approved these changes
LGTM

2025-01-07 07:16 UTC, alexsu52 commented
@devesh-2002, please, fix pre-commit linters

2025-01-07 08:42 UTC, merged

2025-01-07 08:44 UTC, MaximProshin commented
@devesh-2002 , thanks for your contribution!

2025-01-07 10:05 UTC, devesh-2002 commented
Thank you @MaximProshin @alexsu52 for all the help!