QAT example for TF backend,
openvinotoolkit/nncf pull request #3164
Opened 2024-12-20 09:12 UTC by andrey-churkin

### Changes

### Reason for changes

### Related tickets

### Tests

2025-01-07 10:43 UTC, alexsu52 requested changes

2025-01-07 10:43 UTC, alexsu52 commented on examples/quantization_aware_training/tensorflow/mobilenet_v2/main.py
> +tf_quantized_model = nncf.quantize(tf_model, calibration_dataset)
`nncf.quantize` applies the strip transformation for the returned `tf_qunaized_model`. This will lead to incorrect results during training. I suggest to remove applying the strip transformation from `nncf.quantize` and apply this one before converting model to OpenVINO.

2025-01-14 11:28 UTC, andrey-churkin commented on examples/quantization_aware_training/tensorflow/mobilenet_v2/main.py
> +tf_quantized_model = nncf.quantize(tf_model, calibration_dataset)
Done

2025-01-15 10:31 UTC, MaximProshin commented
@daniil-lyakhov , please also review it

2025-01-15 12:21 UTC, daniil-lyakhov commented on examples/quantization_aware_training/tensorflow/mobilenet_v2/main.py
> +# Copyright (c) 2024 Intel Corporation
```suggestion
# Copyright (c) 2025 Intel Corporation
```

2025-01-15 12:21 UTC, daniil-lyakhov commented on examples/quantization_aware_training/tensorflow/mobilenet_v2/main.py
> +    image = tf.compat.v1.image.resize(
Can we use https://www.tensorflow.org/api_docs/python/tf/image/resize instead of `tf.compat.v1.image.resize`?  Looks like unique param `align_corners=False` does not do anything with the image and it safe to migrate to the newest API

2025-01-15 12:21 UTC, daniil-lyakhov commented on examples/quantization_aware_training/tensorflow/mobilenet_v2/main.py
> +    return image, label
```suggestion
    image = tf.image.convert_image_dtype(image, tf.float32)
    label = tf.one_hot(label, DATASET_CLASSES)
    return image, label
```

2025-01-15 12:21 UTC, daniil-lyakhov commented on examples/quantization_aware_training/tensorflow/mobilenet_v2/main.py
> +print(f"Performance speed up (throughput mode): {int8_fps / fp32_fps:.3f}")
Similar Torch quantization aware training example outputs a table with results. Maybe we can align the examples and use the same table format here IMHO
https://github.com/openvinotoolkit/nncf/blob/develop/examples/quantization_aware_training/torch/resnet18/main.py#L338-L355

2025-01-15 12:21 UTC, daniil-lyakhov commented on nncf/tensorflow/strip.py
> +    """
Please fill the docstring with parameters/output value

2025-01-16 09:49 UTC, andrey-churkin commented on nncf/tensorflow/strip.py
> +    wrapped_layers = collect_wrapped_layers(model)
@alexsu52 I just want to highlight. I will move the `nncf.strip(`) call inside the `convert_model()` function, as we discussed. This means that the method will be called for every TensorFlow (TF) model, whether quantized or not. The `collect_wrapped_layers()` function will be called (for any TF model) to check if there are any of our layers. It traverses all layers.

2025-01-16 09:56 UTC, andrey-churkin commented on examples/quantization_aware_training/tensorflow/mobilenet_v2/main.py
> +# Copyright (c) 2024 Intel Corporation
Done

2025-01-16 09:56 UTC, andrey-churkin commented on examples/quantization_aware_training/tensorflow/mobilenet_v2/main.py
> +    image = tf.compat.v1.image.resize(
Done

2025-01-16 09:56 UTC, andrey-churkin commented on examples/quantization_aware_training/tensorflow/mobilenet_v2/main.py
> +    return image, label
Done

2025-01-16 09:58 UTC, andrey-churkin commented on examples/quantization_aware_training/tensorflow/mobilenet_v2/main.py
> +print(f"Performance speed up (throughput mode): {int8_fps / fp32_fps:.3f}")
This example is aligned with the TF PTQ example. As far as I know, there are no requirements for aligning examples across backends. If there are, let's discuss them.

2025-01-16 09:58 UTC, andrey-churkin commented on nncf/tensorflow/strip.py
> +    """
Done

2025-01-16 10:04 UTC, alexsu52 commented on nncf/tensorflow/strip.py
> +def strip(model: tf.keras.Model, do_copy: bool = True) -> tf.keras.Model:
Please add tests for this function.

2025-01-16 10:24 UTC, daniil-lyakhov approved these changes

2025-01-16 10:34 UTC, andrey-churkin commented on examples/quantization_aware_training/tensorflow/mobilenet_v2/main.py
> +ov_quantized_model = ov.convert_model(stripped_model, share_weights=False)
Done

2025-01-16 14:00 UTC, andrey-churkin commented on nncf/tensorflow/strip.py
> +def strip(model: tf.keras.Model, do_copy: bool = True) -> tf.keras.Model:
Done

2025-01-16 15:06 UTC, alexsu52 approved these changes
LGTM

2025-01-16 15:06 UTC, merged