Compression statistics before training
openvinotoolkit/nncf pull request #345
Opened 2020-12-09 18:34 UTC by SKholkin

CompressionController.statistics() are called before training or testing so now you can view some helpful info right after initialization.
RB-Sparsity algorithm and other sparsity/pruning ones despite doubts provide vaild statistics before training.

2020-12-09 18:42 UTC, ljaljushkin requested changes

2020-12-09 18:42 UTC, ljaljushkin commented on examples/classification/main.py
> +    print_statistics(compression_ctrl.statistics())
please do it for other samples as well

2020-12-09 21:15 UTC, ljaljushkin commented on examples/classification/main.py
> +    print_statistics(compression_ctrl.statistics())
don't forget about staged_worker

2020-12-10 09:37 UTC, ljaljushkin commented on examples/classification/main.py
> +    print_statistics(compression_ctrl.statistics())
but before this, please add a check that this method is called in the sanity tests (on train and eval mode, not called on export to onnx)
should be straightforward with mocker.patch:

```
mocked_printing = mocker.patch('examples.common.utils.print_statistics')
mocked_printing.assert_called_once_with()
```

2020-12-11 16:55 UTC, SKholkin commented on tests/test_sanity_sample.py
> +        config['max_iter'] = 1
Because of conflict with object_detection training pipeline structure

2020-12-11 17:52 UTC, ljaljushkin requested changes

2020-12-11 17:52 UTC, ljaljushkin commented on examples/object_detection/main.py
> +    if is_on_first_rank(config):
please align with other samples
```
if is_main_process():
```

2020-12-11 17:52 UTC, ljaljushkin commented on examples/semantic_segmentation/main.py
> +    print_statistics(compression_ctrl.statistics())
please align with other samples
```
if is_main_process():
```

2020-12-11 17:52 UTC, ljaljushkin commented on tests/test_sanity_sample.py
> +    assert mocked_printing.call_count == 2
why are there 2 calls? the number of active GPUs? have you tried on 1 and 3 GPUs?

2020-12-11 17:52 UTC, ljaljushkin commented on examples/object_detection/main.py
> +    config.test_interval = min(config.test_interval, config['max_iter'] - config.start_iter)
please don't change this logic. just print statistics before train and test

2020-12-21 10:07 UTC, SKholkin commented on examples/semantic_segmentation/main.py
> +    print_statistics(compression_ctrl.statistics())
resolved

2020-12-21 10:12 UTC, ljaljushkin approved these changes

2020-12-21 10:30 UTC, SKholkin commented
No need to merge all commits, please squish them.

2020-12-21 12:57 UTC, merged