Print flops pruning level in statistic
openvinotoolkit/nncf pull request #367
Opened 2020-12-25 11:06 UTC by AlexanderDokuchaev

2020-12-25 13:15 UTC, mkaglins requested changes

2020-12-25 13:15 UTC, mkaglins commented on nncf/pruning/filter_pruning/algo.py
> +    def _calculate_flops_pruned_model_by_masks(self):
Please, add any tests on this statistic calculation.

2020-12-25 13:15 UTC, mkaglins commented on nncf/pruning/filter_pruning/algo.py
> +        flops = self._calculate_flops_pruned_model_by_masks()
Here you can re-use pruning rate as FLOPs in case of `self.prune_flops == True`

2021-01-12 21:43 UTC, AlexanderDokuchaev commented
Jenkins please retry a build

2021-01-13 12:45 UTC, AlexKoff88 commented on nncf/utils.py
> +        if len(input_[0].shape) == 1:
Please add a comment that explains the need for this change.

2021-01-13 13:28 UTC, AlexKoff88 commented
Can you please provide an example of new output?

2021-01-13 13:29 UTC, AlexKoff88 reviewed
Please resolve the comments from Maria.

2021-01-13 13:46 UTC, AlexanderDokuchaev commented
@AlexKoff88 add example of output in PR comment.

2021-01-14 13:28 UTC, merged