Update install instruction
openvinotoolkit/nncf pull request #469
Opened 2021-02-01 08:47 UTC by aleksei-kashapov

2021-02-01 12:17 UTC, vshampor requested changes

2021-02-01 12:17 UTC, vshampor commented on tests/test_install.py
> +        subprocess.call("{} install --upgrade pip".format(pip_with_venv), shell=True)
You are running this line in a wrong venv.

2021-02-02 11:09 UTC, aleksei-kashapov commented
@vshampor please have a look

2021-02-02 11:59 UTC, vshampor commented
@aleksei-kashapov please restore the additional installation test that used -m venv.

2021-02-02 12:15 UTC, aleksei-kashapov commented
> @aleksei-kashapov please restore the additional installation test that used -m venv.

Do we really need them? They take time to pass

2021-02-02 13:14 UTC, vshampor commented
@aleksei-kashapov we really need them since `-m venv` is in fact becoming a standard way to create new virtual environments. However, we shouldn't remove `virtualenv` testing either - it is still a viable option for users and, as you've discovered, it may act differently than `-m venv`.

2021-02-03 09:21 UTC, vshampor approved these changes

2021-02-03 09:21 UTC, merged