Remove redundant pruning statistics. Align statistics report
openvinotoolkit/nncf pull request #801
Opened 2021-06-24 21:27 UTC by evgeniya-egupova

2021-06-28 00:12 UTC, evgeniya-egupova commented
Jenkins please retry a build

2021-06-28 08:21 UTC, alexsu52 commented
@evgeniya-egupova Could you provide before/after comparision?

2021-06-30 12:43 UTC, vshampor approved these changes

2021-06-30 13:47 UTC, alexsu52 requested changes

2021-06-30 13:47 UTC, alexsu52 commented on examples/tensorflow/classification/main.py
> +
Could you log statistics using Compression_callbacks for the training step? Explicitly logging statistics before evaluation is good for me and doesn't require changes in this PR.

2021-07-02 08:20 UTC, alexsu52 approved these changes

2021-07-02 08:20 UTC, alexsu52 commented
Jenkins please retry a build

2021-07-02 13:46 UTC, evgeniya-egupova commented
Jenkins please retry a build

2021-07-05 07:49 UTC, merged