Added TF test install
openvinotoolkit/nncf pull request #813
Opened 2021-07-01 06:38 UTC by l-bat

2021-07-01 08:26 UTC, vshampor requested changes

2021-07-01 08:26 UTC, vshampor commented on tests/tensorflow/conftest.py
> +def tmp_venv_with_nncf(tmp_path, package_type, venv_type):  # pylint:disable=redefined-outer-name
This looks very much like its counterpart in torch tests. Can this be refactored to increase code reuse between framework-specific tests?

2021-07-02 08:12 UTC, l-bat commented
Jenkins please retry a build

2021-07-02 14:48 UTC, l-bat commented
Jenkins please retry a build

2021-07-03 09:10 UTC, vshampor approved these changes

2021-07-03 09:10 UTC, vshampor commented on tests/tensorflow/conftest.py
> +        "--run-install-tests", type=str, help="To run installation tests"
Make sure that CI knows about this, later on.

2021-07-03 09:10 UTC, merged