Documentation for Knowledge Distillation
openvinotoolkit/nncf pull request #832
Opened 2021-07-08 06:18 UTC by ljaljushkin

2021-07-09 07:12 UTC, vshampor requested changes

2021-07-09 07:12 UTC, vshampor commented on examples/torch/classification/configs/pruning/resnet34_pruning_geometric_median_kd.json
> +                "weight_importance": "geometric_median"
Should read `"filter_importance"`

2021-07-09 07:29 UTC, alexsu52 commented on docs/compression_algorithms/KnowledgeDistillation.md
> +transferring. The goal is to improve the accuracy of the student network.
```suggestion
transfer. The goal is to improve the accuracy of the student network. 
```

2021-07-09 08:12 UTC, ljaljushkin commented on examples/torch/classification/configs/pruning/resnet34_pruning_geometric_median_kd.json
> +                "weight_importance": "geometric_median"
Done

2021-07-09 08:12 UTC, ljaljushkin commented on docs/compression_algorithms/KnowledgeDistillation.md
> +transferring. The goal is to improve the accuracy of the student network.
Done

2021-07-09 08:35 UTC, alexsu52 approved these changes

2021-07-12 07:01 UTC, vshampor approved these changes

2021-07-12 10:40 UTC, ljaljushkin commented
please merge

2021-07-12 10:56 UTC, merged