Updated nncf_config with command line arguments
openvinotoolkit/nncf pull request #838
Opened 2021-07-08 18:45 UTC by l-bat

2021-07-09 06:25 UTC, alexsu52 requested changes

2021-07-09 06:25 UTC, alexsu52 commented on examples/tensorflow/common/sample_config.py
> +        if key in nncf_config:
If batch_size is not in nncf_config you should add it into the nncf_config too.

2021-07-09 06:28 UTC, vshampor commented
Why would we want to mix the sample configuration and the NNCF configuration again on a same hierarchy level? I separated the `SampleConfig` from `NNCFConfig` for this exact reason. Better to make "nncf_config" a separate field in all sample .json files.

2021-07-09 07:11 UTC, l-bat commented
> Why would we want to mix the sample configuration and the NNCF configuration again on a same hierarchy level? I separated the `SampleConfig` from `NNCFConfig` for this exact reason. Better to make "nncf_config" a separate field in all sample .json files.

`SampleConfig` can not be used because it does not pass validation using json schema. We can dump `NNCFConfig` during training and load it for testing

2021-07-09 08:52 UTC, alexsu52 commented
> 
> 
> > Why would we want to mix the sample configuration and the NNCF configuration again on a same hierarchy level? I separated the `SampleConfig` from `NNCFConfig` for this exact reason. Better to make "nncf_config" a separate field in all sample .json files.
> 
> `SampleConfig` can not be used because it does not pass validation using json schema. We can dump `NNCFConfig` during training and load it for testing

@

2021-07-09 11:30 UTC, alexsu52 approved these changes

2021-07-12 11:26 UTC, vshampor approved these changes

2021-07-12 11:26 UTC, merged