Knowledge Distillation bug fixes
openvinotoolkit/nncf pull request #881
Opened 2021-08-06 07:46 UTC by SKholkin

Changes:

- Fixes failure of running Knowledge Distillation in DataParallel mode. More precisely fixing tensor device placing logic.
- Fixes failure of Knowledge Distillation tests for CPU only case.
- Changing logic of storage Knowledge Distillation loss values. Now compression_ctrl.loss() may be called many times per one iteration.

2021-08-06 07:57 UTC, ljaljushkin commented
new tests are missing. please add

2021-08-06 08:14 UTC, ljaljushkin requested changes

2021-08-06 08:14 UTC, ljaljushkin commented on nncf/torch/knowledge_distillation/knowledge_distillation_loss.py
> +            warnings.warn("Empty list of loss tensors for Knowledge Distillation Loss.", RuntimeWarning)
```suggestion
            warnings.warn("Knowledge Distillation Loss is not calculated.", RuntimeWarning)
```

2021-08-06 08:14 UTC, ljaljushkin commented on nncf/torch/knowledge_distillation/knowledge_distillation_loss.py
> +            return torch.zeros([], device='cpu')
why cpu?

2021-08-09 11:03 UTC, SKholkin commented on nncf/torch/knowledge_distillation/knowledge_distillation_loss.py
> +            warnings.warn("Empty list of loss tensors for Knowledge Distillation Loss.", RuntimeWarning)
Done

2021-08-09 11:04 UTC, SKholkin commented on nncf/torch/knowledge_distillation/knowledge_distillation_loss.py
> +            return torch.zeros([], device='cpu')
This code block was deleted at all

2021-08-09 11:05 UTC, SKholkin commented
> new tests are missing. please add

i've added special test for device related logic.

2021-08-09 14:59 UTC, FyodorK commented
Jenkins please retry a build

2021-08-10 06:37 UTC, SKholkin commented
Jenkins please retry a build

2021-08-11 10:31 UTC, vshampor requested changes

2021-08-11 10:31 UTC, vshampor commented on tests/torch/test_knowledge_distillation.py
> +        return
Use `pytest.skip` instead and give a reason why the test is skipped, like it is being done in other tests.

2021-08-11 13:41 UTC, vshampor approved these changes

2021-08-11 20:31 UTC, merged